### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by alexeyfadeev** [postgrespro/jsquery#16]
I need help in building JsQuery extension for Windows to use with PostgreSQL 9.4 for Windows.

**Comment by akorotkov** [comment]
Could you try this instruction?

https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_Microsoft_Visual_Studio

**Comment by alexeyfadeev** [comment]
I will try. Thanks!

**Comment by alexeyfadeev** [comment]
I have done it. Works fine.

I have forked and made branch 'windows' with Visual Studio project.
https://github.com/alexeyfadeev/jsquery

Win Flex-bison is required for compilation. Installing instruction here: http://sourceforge.net/p/winflexbison/wiki/Visual%20Studio%20custom%20build%20rules/

After install open [win flex-bison folder]/custom_build_rules/win_flex_bison_custom_build.props
Change <OutputFile>%(Filename).tab.cpp</OutputFile> to <OutputFile>%(Filename).c</OutputFile>
<DefinesFile>%(Filename).tab.h</DefinesFile> to <DefinesFile>%(Filename).h</DefinesFile>
<OutputFile>%(Filename).flex.c</OutputFile> to <OutputFile>%(Filename).c</OutputFile>
