### ISSUE TITLE
Contained in operator (<@) does not work

### ISSUE THREAD

**Issue by alekbarszczewski** [postgrespro/jsquery#19]
```sql
create extension if not exists jsquery;
drop table if exists contained_test;
create table contained_test (data jsonb);
insert into contained_test values ('{"id": 1}'), ('{"id": 2}');
select * from contained_test where data @@ 'id IN (1, 2)'::jsquery; -- works, returning both records
select * from contained_test where data @@ 'id <@ [1, 2]'::jsquery; -- does not work, returning 0 rows
```

Using Jsquery 1.0 (compiled few days ago from master).

In readme it states that Jsquery supports "contained in" (<@) operator. Am I doing something wrong?

**Comment by akorotkov** [comment]
<@, @> and && operators should be used when both operands are arrays. In your example left operand is scalar, this is why operators return false.
For instance, in the following example both records will be returned.
```sql
drop table if exists contained_test;
create table contained_test (data jsonb);
insert into contained_test values ('{"id": [1]}'), ('{"id": [2]}');
select * from contained_test where data @@ 'id <@ [1, 2]'::jsquery;
```

**Comment by alekbarszczewski** [comment]
@akorotkov Thanks! Shouldn't `<non_array> <@ [...]` throw error then?

**Comment by feodor** [comment]
Json could be very variadic and we think that jsquery should not emit any error 
if struct of jsonb is differ that jsquery thinks.

Aleksander Barszczewski wrote:
> @akorotkov <https://github.com/akorotkov> Thanks! Shouldn't |<non_array> <@
> [...]| throw error then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/postgrespro/jsquery/issues/19#issuecomment-147727879>.
>

-- 
Teodor Sigaev                                   E-mail: teodor@sigaev.ru
                                                    WWW: http://www.sigaev.ru/

**Comment by alekbarszczewski** [comment]
Ok thanks.
