### ISSUE TITLE
Build Error: Missing jsquery_gram.h

### ISSUE THREAD

**Issue by 3dmashup** [postgrespro/jsquery#20]
Build on Ubuntu 14  and Postgres 9.5 

~/jsquery$ make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer -fpic -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o jsquery_gram.o jsquery_gram.c
jsquery_gram.y:50:26: fatal error: jsquery_gram.h: No such file or directory
 #include <jsquery_gram.h>

**Comment by electric-al** [comment]
+1 Any fix?

**Comment by bvenkat** [comment]
I was able to compile it by reversing the order in the Makefile so that it reads as below:

jsquery_gram.c: BISONFLAGS += -d

jsquery_gram.o: jsquery_scan.c

Maybe you can give it a shot.

**Comment by soledaddiez** [comment]
HI. +1 here.
I tried @bvenkat solution but still getting: 

```
~/jsquery make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -O2  -I. -I./ -I/Library/PostgreSQL/9.5/include/postgresql/server -I/Library/PostgreSQL/9.5/include/postgresql/internal -I/opt/local/20150618/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o jsquery_gram.o jsquery_gram.c
jsquery_gram.y:50:10: fatal error: 'jsquery_gram.h' file not found
#include <jsquery_gram.h>
         ^
1 error generated.
make: *** [jsquery_gram.o] Error 1
```

Any idea?. Is it working for you now @electric-al ?

**Comment by sokolcati** [comment]
Please, check your environment variables, especially the PATH (most likely you need to run: 'export PATH=/usr/local/pgsql/bin:$PATH'). Also check the location of the installed module (contrib/jsquery). You may need 'make clean' before repeated installation. I had the described build problem with missing jsquery_gram.h, but the steps I indicated helped me to solve it. I wish you good luck with further installation of the jsquery module.
