### ISSUE TITLE
PG12+PG16 support

### ISSUE THREAD

**Issue by df7cb** [postgrespro/jsquery#36]
Hi,
could we have a new release with PG12 support so I can update the Debian packages?
Thanks!

**Comment by df7cb** [comment]
Ping!

**Comment by connec** [comment]
Another ping!

It would be great to have a tagged version in order to depend on a particular tag rather than `master`/a commit SHA.

**Comment by df7cb** [comment]
Hi,
I see that PG16 support is fixed with 40b1db58b3f3. Could you please tag a new release so people (and Debian) can actually benefit from the fix?
Thanks!
