### ISSUE TITLE
error with postgresql 15

### ISSUE THREAD

**Issue by murdegern** [postgrespro/jsquery#41]
This happens when loading the extension (compiling it works without warning nor error):

tmp=# create extension jsquery;
ERROR:  could not load library "/think/cs/re/2022-11-DB15_rh7/lib/postgresql/jsquery.so": /think/cs/re/2022-11-DB15_rh7/lib/postgresql/jsquery.so: undefined symbol: pg_atoi

Grepping for pg_atoi in pg 15's sources comes up empty, so it seems this symbol was removed.

Compiling jsquery did not raise any warnings, though.

**Comment by murdegern** [comment]
This mini patch should fix the problem.

[fixit.patch.txt](https://github.com/postgrespro/jsquery/files/9990708/fixit.patch.txt)

**Comment by sokolcati** [comment]
Hi! Thank you for your interest in this extension.
This error was fixed during the jsquery update after the release of PostgreSQL 15 (commit e45ff38).
I am closing this issue. If you have any questions or suggestions for improvements, please do not hesitate to open a new issue.
