### ISSUE TITLE
"make USE_PGXS=1 installcheck " Failed

### ISSUE THREAD

**Issue by didmicang** [postgrespro/jsquery#44]
Hi 
I try to run the regression tests after installing jsquery and it fails with the error message 
_>>
+ERROR:  operator is not unique: jsonb @@ unknown
+LINE 1: select '{"a": {"b": 1}}'::jsonb @@ 'a.* > 0';
+HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
<<_
Can you help me to solve this problem ?
Thanks in advance

**Comment by sokolcati** [comment]
Hi!
What version of PostgreSQL are you using?
