### ISSUE TITLE
Building for Ubuntu 14.04 

### ISSUE THREAD

**Issue by jakejscott** [postgrespro/jsquery#8]
I had to install a couple other packages

`sudo apt-get install postgresql-server-dev-all`
`sudo apt-get install flex`
`sudo apt-get install bison`

**Comment by akorotkov** [comment]
Requirement of PostgreSQL development package was mentioned in README. I've recently added flex and bison requirement into README. Could you, please, tell which version of flex and bison did you use in Ubuntu 14.04?

    flex --version
    bison --version

**Comment by sokolcati** [comment]
I'm closing the issue due to lack of details. Please open a new one if necessary.
